package com.sbm.mc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservationNameAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationNameAllPropertiesEquals(ReservationName expected, ReservationName actual) {
        assertReservationNameAutoGeneratedPropertiesEquals(expected, actual);
        assertReservationNameAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationNameAllUpdatablePropertiesEquals(ReservationName expected, ReservationName actual) {
        assertReservationNameUpdatableFieldsEquals(expected, actual);
        assertReservationNameUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationNameAutoGeneratedPropertiesEquals(ReservationName expected, ReservationName actual) {
        assertThat(expected)
            .as("Verify ReservationName auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationNameUpdatableFieldsEquals(ReservationName expected, ReservationName actual) {
        assertThat(expected)
            .as("Verify ReservationName relevant properties")
            .satisfies(e -> assertThat(e.getResort()).as("check resort").isEqualTo(actual.getResort()))
            .satisfies(e -> assertThat(e.getResvNameId()).as("check resvNameId").isEqualTo(actual.getResvNameId()))
            .satisfies(e -> assertThat(e.getNameId()).as("check nameId").isEqualTo(actual.getNameId()))
            .satisfies(e -> assertThat(e.getNameUsageType()).as("check nameUsageType").isEqualTo(actual.getNameUsageType()))
            .satisfies(e -> assertThat(e.getContactNameId()).as("check contactNameId").isEqualTo(actual.getContactNameId()))
            .satisfies(e -> assertThat(e.getInsertDate()).as("check insertDate").isEqualTo(actual.getInsertDate()))
            .satisfies(e -> assertThat(e.getInsertUser()).as("check insertUser").isEqualTo(actual.getInsertUser()))
            .satisfies(e -> assertThat(e.getUpdateUser()).as("check updateUser").isEqualTo(actual.getUpdateUser()))
            .satisfies(e -> assertThat(e.getUpdateDate()).as("check updateDate").isEqualTo(actual.getUpdateDate()))
            .satisfies(e -> assertThat(e.getResvStatus()).as("check resvStatus").isEqualTo(actual.getResvStatus()))
            .satisfies(e -> assertThat(e.getCommissionCode()).as("check commissionCode").isEqualTo(actual.getCommissionCode()))
            .satisfies(e -> assertThat(e.getAddressId()).as("check addressId").isEqualTo(actual.getAddressId()))
            .satisfies(e -> assertThat(e.getPhoneId()).as("check phoneId").isEqualTo(actual.getPhoneId()))
            .satisfies(e -> assertThat(e.getFaxYn()).as("check faxYn").isEqualTo(actual.getFaxYn()))
            .satisfies(e -> assertThat(e.getMailYn()).as("check mailYn").isEqualTo(actual.getMailYn()))
            .satisfies(e -> assertThat(e.getPrintRateYn()).as("check printRateYn").isEqualTo(actual.getPrintRateYn()))
            .satisfies(e -> assertThat(e.getReportId()).as("check reportId").isEqualTo(actual.getReportId()))
            .satisfies(e -> assertThat(e.getResvNo()).as("check resvNo").isEqualTo(actual.getResvNo()))
            .satisfies(e -> assertThat(e.getConfirmationNo()).as("check confirmationNo").isEqualTo(actual.getConfirmationNo()))
            .satisfies(e -> assertThat(e.getBeginDate()).as("check beginDate").isEqualTo(actual.getBeginDate()))
            .satisfies(e -> assertThat(e.getEndDate()).as("check endDate").isEqualTo(actual.getEndDate()))
            .satisfies(e -> assertThat(e.getFaxId()).as("check faxId").isEqualTo(actual.getFaxId()))
            .satisfies(e -> assertThat(e.getEmailId()).as("check emailId").isEqualTo(actual.getEmailId()))
            .satisfies(e -> assertThat(e.getEmailYn()).as("check emailYn").isEqualTo(actual.getEmailYn()))
            .satisfies(e -> assertThat(e.getConsumerYn()).as("check consumerYn").isEqualTo(actual.getConsumerYn()))
            .satisfies(e -> assertThat(e.getCreditCardId()).as("check creditCardId").isEqualTo(actual.getCreditCardId()))
            .satisfies(
                e ->
                    assertThat(e.getFinanciallyResponsibleYn())
                        .as("check financiallyResponsibleYn")
                        .isEqualTo(actual.getFinanciallyResponsibleYn())
            )
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()))
            .satisfies(e -> assertThat(e.getIntermediaryYn()).as("check intermediaryYn").isEqualTo(actual.getIntermediaryYn()))
            .satisfies(e -> assertThat(e.getPostingAllowedYn()).as("check postingAllowedYn").isEqualTo(actual.getPostingAllowedYn()))
            .satisfies(e -> assertThat(e.getDisplayColor()).as("check displayColor").isEqualTo(actual.getDisplayColor()))
            .satisfies(e -> assertThat(e.getActualCheckInDate()).as("check actualCheckInDate").isEqualTo(actual.getActualCheckInDate()))
            .satisfies(
                e ->
                    assertThat(e.getTruncActualCheckInDate())
                        .as("check truncActualCheckInDate")
                        .isEqualTo(actual.getTruncActualCheckInDate())
            )
            .satisfies(e -> assertThat(e.getActualCheckOutDate()).as("check actualCheckOutDate").isEqualTo(actual.getActualCheckOutDate()))
            .satisfies(
                e ->
                    assertThat(e.getTruncActualCheckOutDate())
                        .as("check truncActualCheckOutDate")
                        .isEqualTo(actual.getTruncActualCheckOutDate())
            )
            .satisfies(e -> assertThat(e.getCreditLimit()).as("check creditLimit").isEqualTo(actual.getCreditLimit()))
            .satisfies(e -> assertThat(e.getAuthorizedBy()).as("check authorizedBy").isEqualTo(actual.getAuthorizedBy()))
            .satisfies(e -> assertThat(e.getParentResvNameId()).as("check parentResvNameId").isEqualTo(actual.getParentResvNameId()))
            .satisfies(e -> assertThat(e.getCancellationNo()).as("check cancellationNo").isEqualTo(actual.getCancellationNo()))
            .satisfies(
                e ->
                    assertThat(e.getCancellationReasonCode())
                        .as("check cancellationReasonCode")
                        .isEqualTo(actual.getCancellationReasonCode())
            )
            .satisfies(
                e ->
                    assertThat(e.getCancellationReasonDesc())
                        .as("check cancellationReasonDesc")
                        .isEqualTo(actual.getCancellationReasonDesc())
            )
            .satisfies(
                e -> assertThat(e.getArrivalTransportType()).as("check arrivalTransportType").isEqualTo(actual.getArrivalTransportType())
            )
            .satisfies(e -> assertThat(e.getArrivalStationCode()).as("check arrivalStationCode").isEqualTo(actual.getArrivalStationCode()))
            .satisfies(e -> assertThat(e.getArrivalCarrierCode()).as("check arrivalCarrierCode").isEqualTo(actual.getArrivalCarrierCode()))
            .satisfies(
                e -> assertThat(e.getArrivalTransportCode()).as("check arrivalTransportCode").isEqualTo(actual.getArrivalTransportCode())
            )
            .satisfies(e -> assertThat(e.getArrivalDateTime()).as("check arrivalDateTime").isEqualTo(actual.getArrivalDateTime()))
            .satisfies(
                e -> assertThat(e.getArrivalEstimateTime()).as("check arrivalEstimateTime").isEqualTo(actual.getArrivalEstimateTime())
            )
            .satisfies(
                e ->
                    assertThat(e.getArrivalTranportationYn())
                        .as("check arrivalTranportationYn")
                        .isEqualTo(actual.getArrivalTranportationYn())
            )
            .satisfies(e -> assertThat(e.getArrivalComments()).as("check arrivalComments").isEqualTo(actual.getArrivalComments()))
            .satisfies(
                e ->
                    assertThat(e.getDepartureTransportType())
                        .as("check departureTransportType")
                        .isEqualTo(actual.getDepartureTransportType())
            )
            .satisfies(
                e -> assertThat(e.getDepartureStationCode()).as("check departureStationCode").isEqualTo(actual.getDepartureStationCode())
            )
            .satisfies(
                e -> assertThat(e.getDepartureCarrierCode()).as("check departureCarrierCode").isEqualTo(actual.getDepartureCarrierCode())
            )
            .satisfies(
                e ->
                    assertThat(e.getDepartureTransportCode())
                        .as("check departureTransportCode")
                        .isEqualTo(actual.getDepartureTransportCode())
            )
            .satisfies(e -> assertThat(e.getDepartureDateTime()).as("check departureDateTime").isEqualTo(actual.getDepartureDateTime()))
            .satisfies(
                e -> assertThat(e.getDepartureEstimateTime()).as("check departureEstimateTime").isEqualTo(actual.getDepartureEstimateTime())
            )
            .satisfies(
                e ->
                    assertThat(e.getDepartureTransportationYn())
                        .as("check departureTransportationYn")
                        .isEqualTo(actual.getDepartureTransportationYn())
            )
            .satisfies(e -> assertThat(e.getDepartureComments()).as("check departureComments").isEqualTo(actual.getDepartureComments()))
            .satisfies(e -> assertThat(e.getCancellationDate()).as("check cancellationDate").isEqualTo(actual.getCancellationDate()))
            .satisfies(e -> assertThat(e.getGuaranteeCode()).as("check guaranteeCode").isEqualTo(actual.getGuaranteeCode()))
            .satisfies(
                e -> assertThat(e.getWlReasonDescription()).as("check wlReasonDescription").isEqualTo(actual.getWlReasonDescription())
            )
            .satisfies(e -> assertThat(e.getWlReasonCode()).as("check wlReasonCode").isEqualTo(actual.getWlReasonCode()))
            .satisfies(e -> assertThat(e.getWlPriority()).as("check wlPriority").isEqualTo(actual.getWlPriority()))
            .satisfies(e -> assertThat(e.getDoNotMoveRoom()).as("check doNotMoveRoom").isEqualTo(actual.getDoNotMoveRoom()))
            .satisfies(e -> assertThat(e.getExternalReference()).as("check externalReference").isEqualTo(actual.getExternalReference()))
            .satisfies(e -> assertThat(e.getPartyCode()).as("check partyCode").isEqualTo(actual.getPartyCode()))
            .satisfies(e -> assertThat(e.getWalkinYn()).as("check walkinYn").isEqualTo(actual.getWalkinYn()))
            .satisfies(e -> assertThat(e.getOriginalEndDate()).as("check originalEndDate").isEqualTo(actual.getOriginalEndDate()))
            .satisfies(
                e ->
                    assertThat(e.getApprovalAmountCalcMethod())
                        .as("check approvalAmountCalcMethod")
                        .isEqualTo(actual.getApprovalAmountCalcMethod())
            )
            .satisfies(e -> assertThat(e.getAmountPercent()).as("check amountPercent").isEqualTo(actual.getAmountPercent()))
            .satisfies(e -> assertThat(e.getNameTaxType()).as("check nameTaxType").isEqualTo(actual.getNameTaxType()))
            .satisfies(e -> assertThat(e.getTaxExemptNo()).as("check taxExemptNo").isEqualTo(actual.getTaxExemptNo()))
            .satisfies(e -> assertThat(e.getRoomFeatures()).as("check roomFeatures").isEqualTo(actual.getRoomFeatures()))
            .satisfies(e -> assertThat(e.getWlTelephoneNo()).as("check wlTelephoneNo").isEqualTo(actual.getWlTelephoneNo()))
            .satisfies(e -> assertThat(e.getVideoCheckoutYn()).as("check videoCheckoutYn").isEqualTo(actual.getVideoCheckoutYn()))
            .satisfies(e -> assertThat(e.getDiscountAmt()).as("check discountAmt").isEqualTo(actual.getDiscountAmt()))
            .satisfies(e -> assertThat(e.getDiscountPrcnt()).as("check discountPrcnt").isEqualTo(actual.getDiscountPrcnt()))
            .satisfies(e -> assertThat(e.getDiscountReasonCode()).as("check discountReasonCode").isEqualTo(actual.getDiscountReasonCode()))
            .satisfies(e -> assertThat(e.getCommissionPaid()).as("check commissionPaid").isEqualTo(actual.getCommissionPaid()))
            .satisfies(e -> assertThat(e.getCommissionHoldCode()).as("check commissionHoldCode").isEqualTo(actual.getCommissionHoldCode()))
            .satisfies(e -> assertThat(e.getTruncBeginDate()).as("check truncBeginDate").isEqualTo(actual.getTruncBeginDate()))
            .satisfies(e -> assertThat(e.getTruncEndDate()).as("check truncEndDate").isEqualTo(actual.getTruncEndDate()))
            .satisfies(e -> assertThat(e.getSguestName()).as("check sguestName").isEqualTo(actual.getSguestName()))
            .satisfies(e -> assertThat(e.getMembershipId()).as("check membershipId").isEqualTo(actual.getMembershipId()))
            .satisfies(e -> assertThat(e.getUdfc01()).as("check udfc01").isEqualTo(actual.getUdfc01()))
            .satisfies(e -> assertThat(e.getUdfc02()).as("check udfc02").isEqualTo(actual.getUdfc02()))
            .satisfies(e -> assertThat(e.getUdfc03()).as("check udfc03").isEqualTo(actual.getUdfc03()))
            .satisfies(e -> assertThat(e.getUdfc04()).as("check udfc04").isEqualTo(actual.getUdfc04()))
            .satisfies(e -> assertThat(e.getUdfc05()).as("check udfc05").isEqualTo(actual.getUdfc05()))
            .satisfies(e -> assertThat(e.getUdfc06()).as("check udfc06").isEqualTo(actual.getUdfc06()))
            .satisfies(e -> assertThat(e.getUdfc07()).as("check udfc07").isEqualTo(actual.getUdfc07()))
            .satisfies(e -> assertThat(e.getUdfc08()).as("check udfc08").isEqualTo(actual.getUdfc08()))
            .satisfies(e -> assertThat(e.getUdfc09()).as("check udfc09").isEqualTo(actual.getUdfc09()))
            .satisfies(e -> assertThat(e.getUdfc10()).as("check udfc10").isEqualTo(actual.getUdfc10()))
            .satisfies(e -> assertThat(e.getUdfc11()).as("check udfc11").isEqualTo(actual.getUdfc11()))
            .satisfies(e -> assertThat(e.getUdfc12()).as("check udfc12").isEqualTo(actual.getUdfc12()))
            .satisfies(e -> assertThat(e.getUdfc13()).as("check udfc13").isEqualTo(actual.getUdfc13()))
            .satisfies(e -> assertThat(e.getUdfc14()).as("check udfc14").isEqualTo(actual.getUdfc14()))
            .satisfies(e -> assertThat(e.getUdfc15()).as("check udfc15").isEqualTo(actual.getUdfc15()))
            .satisfies(e -> assertThat(e.getUdfc16()).as("check udfc16").isEqualTo(actual.getUdfc16()))
            .satisfies(e -> assertThat(e.getUdfc17()).as("check udfc17").isEqualTo(actual.getUdfc17()))
            .satisfies(e -> assertThat(e.getUdfc18()).as("check udfc18").isEqualTo(actual.getUdfc18()))
            .satisfies(e -> assertThat(e.getUdfc19()).as("check udfc19").isEqualTo(actual.getUdfc19()))
            .satisfies(e -> assertThat(e.getUdfc20()).as("check udfc20").isEqualTo(actual.getUdfc20()))
            .satisfies(e -> assertThat(e.getUdfc21()).as("check udfc21").isEqualTo(actual.getUdfc21()))
            .satisfies(e -> assertThat(e.getUdfc22()).as("check udfc22").isEqualTo(actual.getUdfc22()))
            .satisfies(e -> assertThat(e.getUdfc23()).as("check udfc23").isEqualTo(actual.getUdfc23()))
            .satisfies(e -> assertThat(e.getUdfc24()).as("check udfc24").isEqualTo(actual.getUdfc24()))
            .satisfies(e -> assertThat(e.getUdfc25()).as("check udfc25").isEqualTo(actual.getUdfc25()))
            .satisfies(e -> assertThat(e.getUdfc26()).as("check udfc26").isEqualTo(actual.getUdfc26()))
            .satisfies(e -> assertThat(e.getUdfc27()).as("check udfc27").isEqualTo(actual.getUdfc27()))
            .satisfies(e -> assertThat(e.getUdfc28()).as("check udfc28").isEqualTo(actual.getUdfc28()))
            .satisfies(e -> assertThat(e.getUdfc29()).as("check udfc29").isEqualTo(actual.getUdfc29()))
            .satisfies(e -> assertThat(e.getUdfc30()).as("check udfc30").isEqualTo(actual.getUdfc30()))
            .satisfies(e -> assertThat(e.getUdfc31()).as("check udfc31").isEqualTo(actual.getUdfc31()))
            .satisfies(e -> assertThat(e.getUdfc32()).as("check udfc32").isEqualTo(actual.getUdfc32()))
            .satisfies(e -> assertThat(e.getUdfc33()).as("check udfc33").isEqualTo(actual.getUdfc33()))
            .satisfies(e -> assertThat(e.getUdfc34()).as("check udfc34").isEqualTo(actual.getUdfc34()))
            .satisfies(e -> assertThat(e.getUdfc35()).as("check udfc35").isEqualTo(actual.getUdfc35()))
            .satisfies(e -> assertThat(e.getUdfc36()).as("check udfc36").isEqualTo(actual.getUdfc36()))
            .satisfies(e -> assertThat(e.getUdfc37()).as("check udfc37").isEqualTo(actual.getUdfc37()))
            .satisfies(e -> assertThat(e.getUdfc38()).as("check udfc38").isEqualTo(actual.getUdfc38()))
            .satisfies(e -> assertThat(e.getUdfc39()).as("check udfc39").isEqualTo(actual.getUdfc39()))
            .satisfies(e -> assertThat(e.getUdfc40()).as("check udfc40").isEqualTo(actual.getUdfc40()))
            .satisfies(e -> assertThat(e.getUdfn01()).as("check udfn01").isEqualTo(actual.getUdfn01()))
            .satisfies(e -> assertThat(e.getUdfn02()).as("check udfn02").isEqualTo(actual.getUdfn02()))
            .satisfies(e -> assertThat(e.getUdfn03()).as("check udfn03").isEqualTo(actual.getUdfn03()))
            .satisfies(e -> assertThat(e.getUdfn04()).as("check udfn04").isEqualTo(actual.getUdfn04()))
            .satisfies(e -> assertThat(e.getUdfn05()).as("check udfn05").isEqualTo(actual.getUdfn05()))
            .satisfies(e -> assertThat(e.getUdfn06()).as("check udfn06").isEqualTo(actual.getUdfn06()))
            .satisfies(e -> assertThat(e.getUdfn07()).as("check udfn07").isEqualTo(actual.getUdfn07()))
            .satisfies(e -> assertThat(e.getUdfn08()).as("check udfn08").isEqualTo(actual.getUdfn08()))
            .satisfies(e -> assertThat(e.getUdfn09()).as("check udfn09").isEqualTo(actual.getUdfn09()))
            .satisfies(e -> assertThat(e.getUdfn10()).as("check udfn10").isEqualTo(actual.getUdfn10()))
            .satisfies(e -> assertThat(e.getUdfn11()).as("check udfn11").isEqualTo(actual.getUdfn11()))
            .satisfies(e -> assertThat(e.getUdfn12()).as("check udfn12").isEqualTo(actual.getUdfn12()))
            .satisfies(e -> assertThat(e.getUdfn13()).as("check udfn13").isEqualTo(actual.getUdfn13()))
            .satisfies(e -> assertThat(e.getUdfn14()).as("check udfn14").isEqualTo(actual.getUdfn14()))
            .satisfies(e -> assertThat(e.getUdfn15()).as("check udfn15").isEqualTo(actual.getUdfn15()))
            .satisfies(e -> assertThat(e.getUdfn16()).as("check udfn16").isEqualTo(actual.getUdfn16()))
            .satisfies(e -> assertThat(e.getUdfn17()).as("check udfn17").isEqualTo(actual.getUdfn17()))
            .satisfies(e -> assertThat(e.getUdfn18()).as("check udfn18").isEqualTo(actual.getUdfn18()))
            .satisfies(e -> assertThat(e.getUdfn19()).as("check udfn19").isEqualTo(actual.getUdfn19()))
            .satisfies(e -> assertThat(e.getUdfn20()).as("check udfn20").isEqualTo(actual.getUdfn20()))
            .satisfies(e -> assertThat(e.getUdfn21()).as("check udfn21").isEqualTo(actual.getUdfn21()))
            .satisfies(e -> assertThat(e.getUdfn22()).as("check udfn22").isEqualTo(actual.getUdfn22()))
            .satisfies(e -> assertThat(e.getUdfn23()).as("check udfn23").isEqualTo(actual.getUdfn23()))
            .satisfies(e -> assertThat(e.getUdfn24()).as("check udfn24").isEqualTo(actual.getUdfn24()))
            .satisfies(e -> assertThat(e.getUdfn25()).as("check udfn25").isEqualTo(actual.getUdfn25()))
            .satisfies(e -> assertThat(e.getUdfn26()).as("check udfn26").isEqualTo(actual.getUdfn26()))
            .satisfies(e -> assertThat(e.getUdfn27()).as("check udfn27").isEqualTo(actual.getUdfn27()))
            .satisfies(e -> assertThat(e.getUdfn28()).as("check udfn28").isEqualTo(actual.getUdfn28()))
            .satisfies(e -> assertThat(e.getUdfn29()).as("check udfn29").isEqualTo(actual.getUdfn29()))
            .satisfies(e -> assertThat(e.getUdfn30()).as("check udfn30").isEqualTo(actual.getUdfn30()))
            .satisfies(e -> assertThat(e.getUdfn31()).as("check udfn31").isEqualTo(actual.getUdfn31()))
            .satisfies(e -> assertThat(e.getUdfn32()).as("check udfn32").isEqualTo(actual.getUdfn32()))
            .satisfies(e -> assertThat(e.getUdfn33()).as("check udfn33").isEqualTo(actual.getUdfn33()))
            .satisfies(e -> assertThat(e.getUdfn34()).as("check udfn34").isEqualTo(actual.getUdfn34()))
            .satisfies(e -> assertThat(e.getUdfn35()).as("check udfn35").isEqualTo(actual.getUdfn35()))
            .satisfies(e -> assertThat(e.getUdfn36()).as("check udfn36").isEqualTo(actual.getUdfn36()))
            .satisfies(e -> assertThat(e.getUdfn37()).as("check udfn37").isEqualTo(actual.getUdfn37()))
            .satisfies(e -> assertThat(e.getUdfn38()).as("check udfn38").isEqualTo(actual.getUdfn38()))
            .satisfies(e -> assertThat(e.getUdfn39()).as("check udfn39").isEqualTo(actual.getUdfn39()))
            .satisfies(e -> assertThat(e.getUdfn40()).as("check udfn40").isEqualTo(actual.getUdfn40()))
            .satisfies(e -> assertThat(e.getUdfd01()).as("check udfd01").isEqualTo(actual.getUdfd01()))
            .satisfies(e -> assertThat(e.getUdfd02()).as("check udfd02").isEqualTo(actual.getUdfd02()))
            .satisfies(e -> assertThat(e.getUdfd03()).as("check udfd03").isEqualTo(actual.getUdfd03()))
            .satisfies(e -> assertThat(e.getUdfd04()).as("check udfd04").isEqualTo(actual.getUdfd04()))
            .satisfies(e -> assertThat(e.getUdfd05()).as("check udfd05").isEqualTo(actual.getUdfd05()))
            .satisfies(e -> assertThat(e.getUdfd06()).as("check udfd06").isEqualTo(actual.getUdfd06()))
            .satisfies(e -> assertThat(e.getUdfd07()).as("check udfd07").isEqualTo(actual.getUdfd07()))
            .satisfies(e -> assertThat(e.getUdfd08()).as("check udfd08").isEqualTo(actual.getUdfd08()))
            .satisfies(e -> assertThat(e.getUdfd09()).as("check udfd09").isEqualTo(actual.getUdfd09()))
            .satisfies(e -> assertThat(e.getUdfd10()).as("check udfd10").isEqualTo(actual.getUdfd10()))
            .satisfies(
                e ->
                    assertThat(e.getInsertActionInstanceId())
                        .as("check insertActionInstanceId")
                        .isEqualTo(actual.getInsertActionInstanceId())
            )
            .satisfies(e -> assertThat(e.getDmlSeqNo()).as("check dmlSeqNo").isEqualTo(actual.getDmlSeqNo()))
            .satisfies(
                e -> assertThat(e.getBusinessDateCreated()).as("check businessDateCreated").isEqualTo(actual.getBusinessDateCreated())
            )
            .satisfies(e -> assertThat(e.getTurndownYn()).as("check turndownYn").isEqualTo(actual.getTurndownYn()))
            .satisfies(e -> assertThat(e.getRoomInstructions()).as("check roomInstructions").isEqualTo(actual.getRoomInstructions()))
            .satisfies(e -> assertThat(e.getRoomServiceTime()).as("check roomServiceTime").isEqualTo(actual.getRoomServiceTime()))
            .satisfies(e -> assertThat(e.getEventId()).as("check eventId").isEqualTo(actual.getEventId()))
            .satisfies(e -> assertThat(e.getRevenueTypeCode()).as("check revenueTypeCode").isEqualTo(actual.getRevenueTypeCode()))
            .satisfies(e -> assertThat(e.getHurdle()).as("check hurdle").isEqualTo(actual.getHurdle()))
            .satisfies(e -> assertThat(e.getHurdleOverride()).as("check hurdleOverride").isEqualTo(actual.getHurdleOverride()))
            .satisfies(e -> assertThat(e.getRateableValue()).as("check rateableValue").isEqualTo(actual.getRateableValue()))
            .satisfies(
                e -> assertThat(e.getRestrictionOverride()).as("check restrictionOverride").isEqualTo(actual.getRestrictionOverride())
            )
            .satisfies(e -> assertThat(e.getYieldableYn()).as("check yieldableYn").isEqualTo(actual.getYieldableYn()))
            .satisfies(e -> assertThat(e.getSguestFirstname()).as("check sguestFirstname").isEqualTo(actual.getSguestFirstname()))
            .satisfies(e -> assertThat(e.getGuestLastName()).as("check guestLastName").isEqualTo(actual.getGuestLastName()))
            .satisfies(e -> assertThat(e.getGuestFirstName()).as("check guestFirstName").isEqualTo(actual.getGuestFirstName()))
            .satisfies(e -> assertThat(e.getGuestLastNameSdx()).as("check guestLastNameSdx").isEqualTo(actual.getGuestLastNameSdx()))
            .satisfies(e -> assertThat(e.getGuestFirstNameSdx()).as("check guestFirstNameSdx").isEqualTo(actual.getGuestFirstNameSdx()))
            .satisfies(e -> assertThat(e.getChannel()).as("check channel").isEqualTo(actual.getChannel()))
            .satisfies(e -> assertThat(e.getShareSeqNo()).as("check shareSeqNo").isEqualTo(actual.getShareSeqNo()))
            .satisfies(e -> assertThat(e.getGuestSignature()).as("check guestSignature").isEqualTo(actual.getGuestSignature()))
            .satisfies(e -> assertThat(e.getExtensionId()).as("check extensionId").isEqualTo(actual.getExtensionId()))
            .satisfies(e -> assertThat(e.getResvContactId()).as("check resvContactId").isEqualTo(actual.getResvContactId()))
            .satisfies(e -> assertThat(e.getBillingContactId()).as("check billingContactId").isEqualTo(actual.getBillingContactId()))
            .satisfies(e -> assertThat(e.getResInsertSource()).as("check resInsertSource").isEqualTo(actual.getResInsertSource()))
            .satisfies(
                e -> assertThat(e.getResInsertSourceType()).as("check resInsertSourceType").isEqualTo(actual.getResInsertSourceType())
            )
            .satisfies(e -> assertThat(e.getMasterShare()).as("check masterShare").isEqualTo(actual.getMasterShare()))
            .satisfies(e -> assertThat(e.getRegistrationCardNo()).as("check registrationCardNo").isEqualTo(actual.getRegistrationCardNo()))
            .satisfies(e -> assertThat(e.getTiad()).as("check tiad").isEqualTo(actual.getTiad()))
            .satisfies(e -> assertThat(e.getPurposeOfStay()).as("check purposeOfStay").isEqualTo(actual.getPurposeOfStay()))
            .satisfies(e -> assertThat(e.getReinstateDate()).as("check reinstateDate").isEqualTo(actual.getReinstateDate()))
            .satisfies(e -> assertThat(e.getPurgeDate()).as("check purgeDate").isEqualTo(actual.getPurgeDate()))
            .satisfies(e -> assertThat(e.getLastSettleDate()).as("check lastSettleDate").isEqualTo(actual.getLastSettleDate()))
            .satisfies(
                e -> assertThat(e.getLastPeriodicFolioDate()).as("check lastPeriodicFolioDate").isEqualTo(actual.getLastPeriodicFolioDate())
            )
            .satisfies(e -> assertThat(e.getPeriodicFolioFreq()).as("check periodicFolioFreq").isEqualTo(actual.getPeriodicFolioFreq()))
            .satisfies(e -> assertThat(e.getConfirmationLegNo()).as("check confirmationLegNo").isEqualTo(actual.getConfirmationLegNo()))
            .satisfies(e -> assertThat(e.getGuestStatus()).as("check guestStatus").isEqualTo(actual.getGuestStatus()))
            .satisfies(e -> assertThat(e.getGuestType()).as("check guestType").isEqualTo(actual.getGuestType()))
            .satisfies(e -> assertThat(e.getCheckinDuration()).as("check checkinDuration").isEqualTo(actual.getCheckinDuration()))
            .satisfies(e -> assertThat(e.getAuthorizerId()).as("check authorizerId").isEqualTo(actual.getAuthorizerId()))
            .satisfies(e -> assertThat(e.getLastOnlinePrintSeq()).as("check lastOnlinePrintSeq").isEqualTo(actual.getLastOnlinePrintSeq()))
            .satisfies(e -> assertThat(e.getEntryPoint()).as("check entryPoint").isEqualTo(actual.getEntryPoint()))
            .satisfies(e -> assertThat(e.getEntryDate()).as("check entryDate").isEqualTo(actual.getEntryDate()))
            .satisfies(e -> assertThat(e.getPseudoMemType()).as("check pseudoMemType").isEqualTo(actual.getPseudoMemType()))
            .satisfies(
                e -> assertThat(e.getPseudoMemTotalPoints()).as("check pseudoMemTotalPoints").isEqualTo(actual.getPseudoMemTotalPoints())
            )
            .satisfies(e -> assertThat(e.getFolioText1()).as("check folioText1").isEqualTo(actual.getFolioText1()))
            .satisfies(e -> assertThat(e.getFolioText2()).as("check folioText2").isEqualTo(actual.getFolioText2()))
            .satisfies(e -> assertThat(e.getCompTypeCode()).as("check compTypeCode").isEqualTo(actual.getCompTypeCode()))
            .satisfies(e -> assertThat(e.getUniCardId()).as("check uniCardId").isEqualTo(actual.getUniCardId()))
            .satisfies(e -> assertThat(e.getExpCheckinresId()).as("check expCheckinresId").isEqualTo(actual.getExpCheckinresId()))
            .satisfies(e -> assertThat(e.getOriginalBeginDate()).as("check originalBeginDate").isEqualTo(actual.getOriginalBeginDate()))
            .satisfies(e -> assertThat(e.getOwnerFfFlag()).as("check ownerFfFlag").isEqualTo(actual.getOwnerFfFlag()))
            .satisfies(e -> assertThat(e.getCommissionPayoutTo()).as("check commissionPayoutTo").isEqualTo(actual.getCommissionPayoutTo()))
            .satisfies(e -> assertThat(e.getPreChargingYn()).as("check preChargingYn").isEqualTo(actual.getPreChargingYn()))
            .satisfies(e -> assertThat(e.getPostChargingYn()).as("check postChargingYn").isEqualTo(actual.getPostChargingYn()))
            .satisfies(e -> assertThat(e.getPostCoFlag()).as("check postCoFlag").isEqualTo(actual.getPostCoFlag()))
            .satisfies(e -> assertThat(e.getFolioCloseDate()).as("check folioCloseDate").isEqualTo(actual.getFolioCloseDate()))
            .satisfies(e -> assertThat(e.getScheduleCheckoutYn()).as("check scheduleCheckoutYn").isEqualTo(actual.getScheduleCheckoutYn()))
            .satisfies(e -> assertThat(e.getCustomReference()).as("check customReference").isEqualTo(actual.getCustomReference()))
            .satisfies(e -> assertThat(e.getGuaranteeCodePreCi()).as("check guaranteeCodePreCi").isEqualTo(actual.getGuaranteeCodePreCi()))
            .satisfies(e -> assertThat(e.getAwardMembershipId()).as("check awardMembershipId").isEqualTo(actual.getAwardMembershipId()))
            .satisfies(e -> assertThat(e.getEsignedRegCardName()).as("check esignedRegCardName").isEqualTo(actual.getEsignedRegCardName()))
            .satisfies(
                e -> assertThat(e.getStatisticalRoomType()).as("check statisticalRoomType").isEqualTo(actual.getStatisticalRoomType())
            )
            .satisfies(
                e -> assertThat(e.getStatisticalRateTier()).as("check statisticalRateTier").isEqualTo(actual.getStatisticalRateTier())
            )
            .satisfies(e -> assertThat(e.getYmCode()).as("check ymCode").isEqualTo(actual.getYmCode()))
            .satisfies(e -> assertThat(e.getKeyValidUntil()).as("check keyValidUntil").isEqualTo(actual.getKeyValidUntil()))
            .satisfies(e -> assertThat(e.getPreRegisteredYn()).as("check preRegisteredYn").isEqualTo(actual.getPreRegisteredYn()))
            .satisfies(e -> assertThat(e.getTaxRegistrationNo()).as("check taxRegistrationNo").isEqualTo(actual.getTaxRegistrationNo()))
            .satisfies(e -> assertThat(e.getVisaNumber()).as("check visaNumber").isEqualTo(actual.getVisaNumber()))
            .satisfies(e -> assertThat(e.getVisaIssueDate()).as("check visaIssueDate").isEqualTo(actual.getVisaIssueDate()))
            .satisfies(e -> assertThat(e.getVisaExpirationDate()).as("check visaExpirationDate").isEqualTo(actual.getVisaExpirationDate()))
            .satisfies(e -> assertThat(e.getTaxNoOfStays()).as("check taxNoOfStays").isEqualTo(actual.getTaxNoOfStays()))
            .satisfies(e -> assertThat(e.getAsbProratedYn()).as("check asbProratedYn").isEqualTo(actual.getAsbProratedYn()))
            .satisfies(e -> assertThat(e.getAutoSettleDays()).as("check autoSettleDays").isEqualTo(actual.getAutoSettleDays()))
            .satisfies(e -> assertThat(e.getAutoSettleYn()).as("check autoSettleYn").isEqualTo(actual.getAutoSettleYn()))
            .satisfies(
                e -> assertThat(e.getSplitFromResvNameId()).as("check splitFromResvNameId").isEqualTo(actual.getSplitFromResvNameId())
            )
            .satisfies(e -> assertThat(e.getNextDestination()).as("check nextDestination").isEqualTo(actual.getNextDestination()))
            .satisfies(
                e ->
                    assertThat(e.getDateOfArrivalInCountry())
                        .as("check dateOfArrivalInCountry")
                        .isEqualTo(actual.getDateOfArrivalInCountry())
            )
            .satisfies(e -> assertThat(e.getPreArrReviewedDt()).as("check preArrReviewedDt").isEqualTo(actual.getPreArrReviewedDt()))
            .satisfies(e -> assertThat(e.getPreArrReviewedUser()).as("check preArrReviewedUser").isEqualTo(actual.getPreArrReviewedUser()))
            .satisfies(e -> assertThat(e.getBonusCheckId()).as("check bonusCheckId").isEqualTo(actual.getBonusCheckId()))
            .satisfies(e -> assertThat(e.getMobileAudioKeyYn()).as("check mobileAudioKeyYn").isEqualTo(actual.getMobileAudioKeyYn()))
            .satisfies(
                e ->
                    assertThat(e.getDirectBillVerifyResponse())
                        .as("check directBillVerifyResponse")
                        .isEqualTo(actual.getDirectBillVerifyResponse())
            )
            .satisfies(e -> assertThat(e.getAddresseeNameId()).as("check addresseeNameId").isEqualTo(actual.getAddresseeNameId()))
            .satisfies(
                e -> assertThat(e.getSuperSearchIndexText()).as("check superSearchIndexText").isEqualTo(actual.getSuperSearchIndexText())
            )
            .satisfies(e -> assertThat(e.getAutoCheckinYn()).as("check autoCheckinYn").isEqualTo(actual.getAutoCheckinYn()))
            .satisfies(e -> assertThat(e.getEmailFolioYn()).as("check emailFolioYn").isEqualTo(actual.getEmailFolioYn()))
            .satisfies(e -> assertThat(e.getEmailAddress()).as("check emailAddress").isEqualTo(actual.getEmailAddress()))
            .satisfies(
                e ->
                    assertThat(e.getSpgUpgradeConfirmedRoomtype())
                        .as("check spgUpgradeConfirmedRoomtype")
                        .isEqualTo(actual.getSpgUpgradeConfirmedRoomtype())
            )
            .satisfies(
                e -> assertThat(e.getSpgUpgradeReasonCode()).as("check spgUpgradeReasonCode").isEqualTo(actual.getSpgUpgradeReasonCode())
            )
            .satisfies(
                e ->
                    assertThat(e.getSpgSuiteNightAwardStatus())
                        .as("check spgSuiteNightAwardStatus")
                        .isEqualTo(actual.getSpgSuiteNightAwardStatus())
            )
            .satisfies(
                e -> assertThat(e.getSpgDiscloseRoomTypeYn()).as("check spgDiscloseRoomTypeYn").isEqualTo(actual.getSpgDiscloseRoomTypeYn())
            )
            .satisfies(e -> assertThat(e.getAmenityEligibleYn()).as("check amenityEligibleYn").isEqualTo(actual.getAmenityEligibleYn()))
            .satisfies(e -> assertThat(e.getAmenityLevelCode()).as("check amenityLevelCode").isEqualTo(actual.getAmenityLevelCode()))
            .satisfies(
                e -> assertThat(e.getBaseRateCurrencyCode()).as("check baseRateCurrencyCode").isEqualTo(actual.getBaseRateCurrencyCode())
            )
            .satisfies(e -> assertThat(e.getBaseRateCode()).as("check baseRateCode").isEqualTo(actual.getBaseRateCode()))
            .satisfies(
                e -> assertThat(e.getLocalBaseRateAmount()).as("check localBaseRateAmount").isEqualTo(actual.getLocalBaseRateAmount())
            )
            .satisfies(e -> assertThat(e.getPhoneDisplayNameYn()).as("check phoneDisplayNameYn").isEqualTo(actual.getPhoneDisplayNameYn()))
            .satisfies(e -> assertThat(e.getResortChargeNumber()).as("check resortChargeNumber").isEqualTo(actual.getResortChargeNumber()))
            .satisfies(
                e -> assertThat(e.getMobileChkoutAllowed()).as("check mobileChkoutAllowed").isEqualTo(actual.getMobileChkoutAllowed())
            )
            .satisfies(
                e ->
                    assertThat(e.getMobileViewFolioAllowed())
                        .as("check mobileViewFolioAllowed")
                        .isEqualTo(actual.getMobileViewFolioAllowed())
            )
            .satisfies(
                e -> assertThat(e.getHkExpectedServiceTime()).as("check hkExpectedServiceTime").isEqualTo(actual.getHkExpectedServiceTime())
            )
            .satisfies(
                e -> assertThat(e.getEligibleForUpgradeYn()).as("check eligibleForUpgradeYn").isEqualTo(actual.getEligibleForUpgradeYn())
            )
            .satisfies(
                e -> assertThat(e.getBeginSystemDateTime()).as("check beginSystemDateTime").isEqualTo(actual.getBeginSystemDateTime())
            )
            .satisfies(
                e ->
                    assertThat(e.getMobileCheckinAllowedYn())
                        .as("check mobileCheckinAllowedYn")
                        .isEqualTo(actual.getMobileCheckinAllowedYn())
            )
            .satisfies(e -> assertThat(e.getQuoteId()).as("check quoteId").isEqualTo(actual.getQuoteId()))
            .satisfies(
                e -> assertThat(e.getManualCheckoutStatus()).as("check manualCheckoutStatus").isEqualTo(actual.getManualCheckoutStatus())
            )
            .satisfies(
                e ->
                    assertThat(e.getMobilePreferredCurrency())
                        .as("check mobilePreferredCurrency")
                        .isEqualTo(actual.getMobilePreferredCurrency())
            )
            .satisfies(
                e ->
                    assertThat(e.getMobileActionAlertIssued())
                        .as("check mobileActionAlertIssued")
                        .isEqualTo(actual.getMobileActionAlertIssued())
            )
            .satisfies(e -> assertThat(e.getExternalEfolioYn()).as("check externalEfolioYn").isEqualTo(actual.getExternalEfolioYn()))
            .satisfies(e -> assertThat(e.getOptInBatchFolYn()).as("check optInBatchFolYn").isEqualTo(actual.getOptInBatchFolYn()))
            .satisfies(e -> assertThat(e.getFolioAddrElementId()).as("check folioAddrElementId").isEqualTo(actual.getFolioAddrElementId()))
            .satisfies(
                e -> assertThat(e.getOperaEsignedRegCardYn()).as("check operaEsignedRegCardYn").isEqualTo(actual.getOperaEsignedRegCardYn())
            )
            .satisfies(e -> assertThat(e.getResvGuid()).as("check resvGuid").isEqualTo(actual.getResvGuid()))
            .satisfies(e -> assertThat(e.getAdvanceCheckedInYn()).as("check advanceCheckedInYn").isEqualTo(actual.getAdvanceCheckedInYn()))
            .satisfies(
                e -> assertThat(e.getExpectedTimeOfReturn()).as("check expectedTimeOfReturn").isEqualTo(actual.getExpectedTimeOfReturn())
            )
            .satisfies(e -> assertThat(e.getEtrComments()).as("check etrComments").isEqualTo(actual.getEtrComments()))
            .satisfies(e -> assertThat(e.getOptedForCommYn()).as("check optedForCommYn").isEqualTo(actual.getOptedForCommYn()))
            .satisfies(
                e ->
                    assertThat(e.getCreditLimitAutoPayAllowYn())
                        .as("check creditLimitAutoPayAllowYn")
                        .isEqualTo(actual.getCreditLimitAutoPayAllowYn())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationNameUpdatableRelationshipsEquals(ReservationName expected, ReservationName actual) {}
}
