package com.sbm.mc.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class ResortRoomCategoryTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static ResortRoomCategory getResortRoomCategorySample1() {
        return new ResortRoomCategory()
            .id(1L)
            .resort("resort1")
            .roomCategory("roomCategory1")
            .roomClass("roomClass1")
            .numberRooms(1)
            .shortDescription("shortDescription1")
            .longDescription("longDescription1")
            .compiled("compiled1")
            .psuedoRoomType("psuedoRoomType1")
            .replacesCategory("replacesCategory1")
            .orderBy(1)
            .maxOccupancy(1)
            .maxRollaways(1)
            .rateCategory("rateCategory1")
            .label("label1")
            .genericFlag("genericFlag1")
            .suiteYn("suiteYn1")
            .meetingroomYn("meetingroomYn1")
            .insertUser(1)
            .updateUser(1)
            .rateCode("rateCode1")
            .defOccupancy(1)
            .imageId(1)
            .pseudoYn("pseudoYn1")
            .sendToInterfaceYn("sendToInterfaceYn1")
            .yieldableYn("yieldableYn1")
            .yieldCategory("yieldCategory1")
            .housekeeping("housekeeping1")
            .canDeleteYn("canDeleteYn1")
            .roominfoUrl("roominfoUrl1")
            .ownerYn("ownerYn1")
            .autoIncludeYn("autoIncludeYn1")
            .initialRoundUp(1)
            .increments(1)
            .rotationGroup("rotationGroup1")
            .salesFlag("salesFlag1")
            .autoRoomAssignYn("autoRoomAssignYn1")
            .upsellYn("upsellYn1")
            .ormsUpsellRank(1)
            .ormsDrxtraAdult(1)
            .ormsDrxtraChild(1)
            .maxOccupancyAdults(1)
            .maxOccupancyChildren(1)
            .roomPool("roomPool1")
            .memberAwardRoomGrp("memberAwardRoomGrp1")
            .ormsDrxtra2ndAdult(1)
            .ormsDrtier1(1)
            .ormsDrtier2(1)
            .ormsDrtier3(1)
            .autoCheckinYn("autoCheckinYn1")
            .maxFixBedOccupancy(1)
            .maintenanceYn("maintenanceYn1")
            .smokingPreference("smokingPreference1")
            .sLabel("sLabel1")
            .sBedtype("sBedtype1")
            .sellThruRuleYn("sellThruRuleYn1")
            .crsDescription("crsDescription1")
            .evisitorFacilityId("evisitorFacilityId1")
            .minOccupancy(1)
            .accessibleYn("accessibleYn1");
    }

    public static ResortRoomCategory getResortRoomCategorySample2() {
        return new ResortRoomCategory()
            .id(2L)
            .resort("resort2")
            .roomCategory("roomCategory2")
            .roomClass("roomClass2")
            .numberRooms(2)
            .shortDescription("shortDescription2")
            .longDescription("longDescription2")
            .compiled("compiled2")
            .psuedoRoomType("psuedoRoomType2")
            .replacesCategory("replacesCategory2")
            .orderBy(2)
            .maxOccupancy(2)
            .maxRollaways(2)
            .rateCategory("rateCategory2")
            .label("label2")
            .genericFlag("genericFlag2")
            .suiteYn("suiteYn2")
            .meetingroomYn("meetingroomYn2")
            .insertUser(2)
            .updateUser(2)
            .rateCode("rateCode2")
            .defOccupancy(2)
            .imageId(2)
            .pseudoYn("pseudoYn2")
            .sendToInterfaceYn("sendToInterfaceYn2")
            .yieldableYn("yieldableYn2")
            .yieldCategory("yieldCategory2")
            .housekeeping("housekeeping2")
            .canDeleteYn("canDeleteYn2")
            .roominfoUrl("roominfoUrl2")
            .ownerYn("ownerYn2")
            .autoIncludeYn("autoIncludeYn2")
            .initialRoundUp(2)
            .increments(2)
            .rotationGroup("rotationGroup2")
            .salesFlag("salesFlag2")
            .autoRoomAssignYn("autoRoomAssignYn2")
            .upsellYn("upsellYn2")
            .ormsUpsellRank(2)
            .ormsDrxtraAdult(2)
            .ormsDrxtraChild(2)
            .maxOccupancyAdults(2)
            .maxOccupancyChildren(2)
            .roomPool("roomPool2")
            .memberAwardRoomGrp("memberAwardRoomGrp2")
            .ormsDrxtra2ndAdult(2)
            .ormsDrtier1(2)
            .ormsDrtier2(2)
            .ormsDrtier3(2)
            .autoCheckinYn("autoCheckinYn2")
            .maxFixBedOccupancy(2)
            .maintenanceYn("maintenanceYn2")
            .smokingPreference("smokingPreference2")
            .sLabel("sLabel2")
            .sBedtype("sBedtype2")
            .sellThruRuleYn("sellThruRuleYn2")
            .crsDescription("crsDescription2")
            .evisitorFacilityId("evisitorFacilityId2")
            .minOccupancy(2)
            .accessibleYn("accessibleYn2");
    }

    public static ResortRoomCategory getResortRoomCategoryRandomSampleGenerator() {
        return new ResortRoomCategory()
            .id(longCount.incrementAndGet())
            .resort(UUID.randomUUID().toString())
            .roomCategory(UUID.randomUUID().toString())
            .roomClass(UUID.randomUUID().toString())
            .numberRooms(intCount.incrementAndGet())
            .shortDescription(UUID.randomUUID().toString())
            .longDescription(UUID.randomUUID().toString())
            .compiled(UUID.randomUUID().toString())
            .psuedoRoomType(UUID.randomUUID().toString())
            .replacesCategory(UUID.randomUUID().toString())
            .orderBy(intCount.incrementAndGet())
            .maxOccupancy(intCount.incrementAndGet())
            .maxRollaways(intCount.incrementAndGet())
            .rateCategory(UUID.randomUUID().toString())
            .label(UUID.randomUUID().toString())
            .genericFlag(UUID.randomUUID().toString())
            .suiteYn(UUID.randomUUID().toString())
            .meetingroomYn(UUID.randomUUID().toString())
            .insertUser(intCount.incrementAndGet())
            .updateUser(intCount.incrementAndGet())
            .rateCode(UUID.randomUUID().toString())
            .defOccupancy(intCount.incrementAndGet())
            .imageId(intCount.incrementAndGet())
            .pseudoYn(UUID.randomUUID().toString())
            .sendToInterfaceYn(UUID.randomUUID().toString())
            .yieldableYn(UUID.randomUUID().toString())
            .yieldCategory(UUID.randomUUID().toString())
            .housekeeping(UUID.randomUUID().toString())
            .canDeleteYn(UUID.randomUUID().toString())
            .roominfoUrl(UUID.randomUUID().toString())
            .ownerYn(UUID.randomUUID().toString())
            .autoIncludeYn(UUID.randomUUID().toString())
            .initialRoundUp(intCount.incrementAndGet())
            .increments(intCount.incrementAndGet())
            .rotationGroup(UUID.randomUUID().toString())
            .salesFlag(UUID.randomUUID().toString())
            .autoRoomAssignYn(UUID.randomUUID().toString())
            .upsellYn(UUID.randomUUID().toString())
            .ormsUpsellRank(intCount.incrementAndGet())
            .ormsDrxtraAdult(intCount.incrementAndGet())
            .ormsDrxtraChild(intCount.incrementAndGet())
            .maxOccupancyAdults(intCount.incrementAndGet())
            .maxOccupancyChildren(intCount.incrementAndGet())
            .roomPool(UUID.randomUUID().toString())
            .memberAwardRoomGrp(UUID.randomUUID().toString())
            .ormsDrxtra2ndAdult(intCount.incrementAndGet())
            .ormsDrtier1(intCount.incrementAndGet())
            .ormsDrtier2(intCount.incrementAndGet())
            .ormsDrtier3(intCount.incrementAndGet())
            .autoCheckinYn(UUID.randomUUID().toString())
            .maxFixBedOccupancy(intCount.incrementAndGet())
            .maintenanceYn(UUID.randomUUID().toString())
            .smokingPreference(UUID.randomUUID().toString())
            .sLabel(UUID.randomUUID().toString())
            .sBedtype(UUID.randomUUID().toString())
            .sellThruRuleYn(UUID.randomUUID().toString())
            .crsDescription(UUID.randomUUID().toString())
            .evisitorFacilityId(UUID.randomUUID().toString())
            .minOccupancy(intCount.incrementAndGet())
            .accessibleYn(UUID.randomUUID().toString());
    }
}
